- hosts: web
  gather_facts: no
  become: true
  tasks:
  - name: "Stop Apache"
    service:
      name: apache2
      state: stopped
    tags:
    - stop
    - bounce
  - name: "Start Apache"
    service:
      name: apache2
      state: started
    tags:
    - start
    - bounce 
  - name: "Restart Apache"
    service:
      name: apache2
      state: restarted
    tags:
    - restart 
