- hosts: web
  gather_facts: yes
  vars:
  - APACHE_PORT: 8080
  - VAR_TWO: "In playbook"
  vars_files:
  - vars.yml
  tasks:
  - debug:
      msg: "Hello There"
  - debug:
      msg: "VAR_TWO is {{VAR_TWO}}, VAR_THREE is {{VAR_THREE}}"
  - debug:
      msg: "facts: {{ansible_nodename}} {{ansible_os_family}}"
  - command: "service apache2 status"
    become: true
    register: output_var
    ignore_errors: true
  - debug:
      var: output_var.rc
