- hosts: ctrl       
  gather_facts: no
  tasks:
  - name: "Update cache"
    become: yes
    apt:
     update_cache: yes
     cache_valid_time: 36000
  - name: "Install package"
    become: yes
    apt:
      name: git 
      update_cache: no
  - name: "Checkout"
    git:
      repo: "https://github.com/AdityaSP/htmlonly"
      dest: "/tmp/code"

- hosts: web
  gather_facts: no
  vars:
  - APACHE_PORT: 80
  become: true
  tasks:
  - name: "Update cache"
    apt:
     update_cache: yes
     cache_valid_time: 36000
  - name: "Install package"
    apt:
      name: "{{item}}"
      update_cache: no
    with_items:
    - apache2
    - curl
  - name: "Start Apache"
    service:
      name: apache2
      state: started
      enabled: yes
  - name: "Change port"
    lineinfile:
      dest: /etc/apache2/ports.conf
      regexp: "^Listen"
      line: "Listen {{APACHE_PORT}}"
    notify:
    - "Restart service"
  - name: "Deploy code"
    copy:
      src: /tmp/code/mypage.html
      dest: /var/www/html/mypage.html

  handlers:
  - name: "Restart service"
    service:
      name: apache2
      state: restarted


